CREATE DATABASE INLOCK_GAMES_MANHA;

USE INLOCK_GAMES_MANHA;

CREATE TABLE USUARIOS (
	USUARIOID INT PRIMARY KEY IDENTITY,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	TIPOUSUARIO VARCHAR(50) NOT NULL
);

INSERT INTO USUARIOS VALUES ('admin@admin.com', 'admin', 'ADMINISTRADOR'), ('cliente@cliente.com', 'cliente', 'CLIENTE');

CREATE TABLE ESTUDIOS (
	ESTUDIOID INT PRIMARY KEY IDENTITY,
	NOMEESTUDIO VARCHAR(100) NOT NULL
);

INSERT INTO ESTUDIOS VALUES ('Blizzard'), ('Rockstar Studios'),( 'Square Enix');

CREATE TABLE JOGOS (
	JOGOID INT PRIMARY KEY IDENTITY,
	NOMEJOGO VARCHAR(50) NOT NULL,
	DESCRICAO TEXT NOT NULL,
	DATALANCAMENTO DATE NOT NULL,
	VALOR DECIMAL(5,2),
	IMAGEM VARCHAR(250),
	ESTUDIOID INT FOREIGN KEY REFERENCES ESTUDIOS(ESTUDIOID)
);

INSERT INTO JOGOS VALUES 
('Diablo 3','É um jogo que contém bastante ação e é viciante, seja você um novato ou um fã','2012-05-15', '99.00','', 1),
('Red Dead Redemption II','Jogo eletrônico de ação-aventura western','2018-10-26', '120.00','', 2)

